
export enum Category {
  Banish = "Banish",
  ChangeATKDEF = "Change ATK/DEF",
  ChangeLevelRank = "Change Level/Rank",
  Control = "Control",
  CounterRelated = "Counter-related",
  DamageLP = "Damage LP",
  DestroyDeck = "Destroy Deck",
  DestroyHand = "Destroy Hand",
  DestroyMonster = "Destroy Monster",
  DestroyST = "Destroy S/T",
  DirectAttack = "Direct Attack",
  Draw = "Draw",
  FusionRelated = "Fusion-related",
  Gamble = "Gamble",
  LinkRelated = "Link-related",
  MoveZones = "Move Zones",
  MultiAttack = "Multi Attack",
  NegateActivation = "Negate Activation",
  NegateEffect = "Negate Effect",
  NonEffect = "Non-effect",
  Piercing = "Piercing",
  Position = "Position",
  RecoverLP = "Recover LP",
  RitualRelated = "Ritual-related",
  Search = "Search",
  SendToDeck = "Send to Deck",
  SendToGY = "Send to GY",
  SendToHand = "Send to Hand",
  SpecialSummon = "Special Summon",
  SynchroRelated = "Synchro-related",
  TokenRelated = "Token-related",
  XyzRelated = "Xyz-related"
}
