
export enum Race {
  Aqua = "Aqua",
  Beast = "Beast",
  BeastWarrior = "Beast-Warrior",
  CreatorGod = "Creator God",
  Cyberse = "Cyberse",
  Dinosaur = "Dinosaur",
  DivineBeast = "Divine-Beast",
  Dragon = "Dragon",
  Fairy = "Fairy",
  Fiend = "Fiend",
  Fish = "Fish",
  Insect = "Insect",
  Machine = "Machine",
  Plant = "Plant",
  Psychic = "Psychic",
  Pyro = "Pyro",
  Race = "Race",
  Reptile = "Reptile",
  Rock = "Rock",
  SeaSerpent = "Sea Serpent",
  Spellcaster = "Spellcaster",
  Thunder = "Thunder",
  Warrior = "Warrior",
  WingedBeast = "Winged Beast",
  Wyrm = "Wyrm",
  Zombie = "Zombie"
}
